[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
overlapSeconds = 0
drainingSeconds = 0
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
